### ISSUE TITLE
relative layout 하는데 view가 안나와요;

### ISSUE THREAD

**Issue by jshagold** [Jaram2017/android-findpeople#1]
![](https://github.com/Jaram2017/Android_findpeople/blob/SungHak/image_hak/relative%20%EB%AA%A8%EB%A6%84.PNG?raw=true) 코드는 이렇게 짰는데 그림에서 텍스트가 안나와요ㅠㅠ ![](https://github.com/Jaram2017/Android_findpeople/blob/SungHak/image_hak/relative%20%EB%AA%A8%EB%A6%842.PNG?raw=true)

**Comment by YongTaek** [comment]
TextView 말고 전체 XML 코드를 가져와보세요.
RelativeLayout을 사용하는 것같은데 RelativeLayout은 다른 View에 의존 하는게 많기 때문에 전체를 가져오는것이 효과적입니다.

**Comment by jshagold** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/textView4"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:textSize="20dp"
        android:text="TextView"
        android:background="#ffafaf" />

    <TextView
        android:id="@+id/textView5"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/textView4"
        android:textSize="30dp"
        android:text="SuperText"
        android:background="#4441aa"/>

    <TextView
        android:id="@+id/textView6"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="40dp"
        android:text="TestText"
        android:background="#4ca"
        android:layout_toRightOf="@+id/textView5"
        android:layout_below="@id/textView4" />

    <TextView
        android:id="@+id/Blind"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="BLINDTEXT"
        android:textSize="40dp"
        android:background="#4caf50"
        android:layout_below="@id/textView4"
        android:layout_alignParentStart="true"
        android:layout_marginTop="42dp" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@id/Blind"
        android:text="AlignText"
        android:textSize="30dp"
        android:background="#aa3333"
        android:layout_toRightOf="@id/Blind"
        android:layout_below="@id/Blind" />

</RelativeLayout>
전체코드 입니다

**Comment by YongTaek** [comment]
layout_alignBottom 속성은 해당 View의 아랫선을 가르키는 View의 아랫선과 일치시키는 속성입니다.
따라서 layout_alignBottom의 아이디를 Blind로 해두면 Blind의 아랫선과 AlignText의 아랫선이 같아지게 되는데
layout_below속성으로 인해 Blind 밑에 위치하도록 되어 있으므로 위 아래가 같은 위치에 놓이게 되어 글자가 보이지 않는 것입니다.
[참고자료]
https://m.blog.naver.com/PostView.nhn?blogId=sobakr&logNo=60111512004&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F

한글이니 읽어보세요

**Comment by jshagold** [comment]
해결됐네요 감사합니다^^
