### ISSUE TITLE
Tablelayout에서 layout_column을 적용했는데 적용이 제대로 안되는거같아요.

### ISSUE THREAD

**Issue by jshagold** [Jaram2017/android-findpeople#10]
![](https://github.com/Jaram2017/android-findpeople/blob/SungHak/image_hak/homework_img/20170925_issue/%EC%BA%A1%EC%B2%98.PNG?raw=true)  
![](https://github.com/Jaram2017/android-findpeople/blob/SungHak/image_hak/homework_img/20170925_issue/%EC%BA%A1%EC%B2%982.PNG?raw=true)
코드와 예제화면입니다~

**Comment by jshagold** [comment]
<?xml version="1.0" encoding="utf-8"?>
<TableLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TableRow>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="AAA"
            android:textSize="30dp"
            android:background="#ff77aa"/>
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="BBB"
            android:textSize="30dp"
            android:background="#ffff00"/>
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="CCC"
            android:textSize="30dp"
            android:background="#aaafaf"/>
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="DDD"
            android:textSize="30dp"
            android:background="#00aaff"/>

    </TableRow>

    <TableRow
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="#aaffff"
            android:text="111"
            android:textSize="30dp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="#0ffa00"
            android:text="222"
            android:textSize="30dp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="#faaf00"
            android:text="333"
            android:textSize="30dp" />
        <TextView
            android:id="@+id/textView2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_column="7"
            android:background="#afff00"
            android:text="444"
            android:textSize="30dp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="#aa00af"
            android:text="999"
            android:textSize="30dp" />


    </TableRow>


</TableLayout>

**Comment by YongTaek** [comment]
음 조금 더 자세히 적어보도록 하세요.
1. 내가 지금 무엇을 하고 싶은가?
2. 내가 지금 무엇을 시도 했는가?
3. 시도한 결과 어떤 문제(현상)이 발생 했는가?
더 좋은 방법이 있겠지만 우선 위의 흐름대로 질문을 적어보는게 좋을 것같습니다. 이후 코멘트는 질문을 바꿔본 다음에 해보도록 합시다.

**Comment by YongTaek** [comment]
조금 더 첨부하자면 지금 stretchColumn 의 적용에 관한 질문을 하고 있는데 stretchColumn 을 몇으로 했는지 조차 질문에 나와있지 않네요.

**Comment by jshagold** [comment]
444라고 적힌 column을 8번째 열의 위치로 이동시키고 싶어서 android:layout_column="7"로 작성했는데 
블로그의 예시와는 다르게 7번째로 안가고  5번째로만 이동되네요;; 
[제목을 잘못작성했네요; 위키쓰다가 혼동이왔나봐요]

블로그 예시= ![](https://github.com/Jaram2017/android-findpeople/blob/SungHak/image_hak/homework_img/20170925_issue/%EC%BA%A1%EC%B2%983.PNG?raw=true)

**Comment by YongTaek** [comment]
우선 tablelayout에는 빈 공간이 생길 경우 말그대로 빈 공간이 들어가게 됩니다. 하지만 이 경우 말그대로 빈 공간이기 때문에 아무런 표가 나질 않죠. 하지만 하나의 column의 공간을 정하고자 할 때 자신의 공간을 모르면 위의 row를 따릅니다.
잘 이해가 되지 않는다면
```
<TableRow>
    <TextView
         width: 30dp/>
    <TextView
         width: 30dp/>
</TableRow>
<TableRow>
    <TextView
         width: wrap_content/>
    <TextView
         width: 30dp/>
</TableRow>
```
이런식으로 작성해보세요.
두번째 Row의 첫 번째 column이 맨 위의 처음 column의 넓이와 같게 될것입니다.

**Comment by YongTaek** [comment]
위의 과정을 따라했을 때 저렇게 작동되는 상황을 알게 되었다면 자연스럽게 해답을 얻게 될 것입니다.
layout_column=7로 지정했지만 실제로 위의 경우 처음 Row는 View가 4개가 있고 밑에는 3개 이후 하나를 7로 작성한 상태인데,
4번째 빈 공간의 경우 위에 column이 있기 때문에 빈 공간을 만들 수 있지만 5,6번째의 경우 위에 column이 없기 때문에 공간을 만들지 못하는 것입니다.
이를 해결하기 위해선 column이 자신의 공간 이상으로 뻗어나갈 수 있는 속성 즉 stretchColumns를 써보도록 하세요.

**Comment by jshagold** [comment]
stretch를 빈 열번호에 지정을 해야하네요 거지같네^^
