### ISSUE TITLE
TableLayout에서 stretchColumns는 범위로 지정할 수 있습니다.

### ISSUE THREAD

**Issue by YongTaek** [Jaram2017/android-findpeople#11]
범위 지정하는 법을 코멘트로 달아본 뒤 close하면 좋을 것같습니다.

**Comment by YongTaek** [comment]
성학이 위키에 적혀 있네요 전체에 대해 어떻게 적용하는지 여기에 코멘트로 남긴뒤 close해주시길 바랍니다.

**Comment by jshagold** [comment]
stretchColumns 범위지정은
android:stretchColumns="숫자"를 tablelayout에 표기하고 숫자에 지정하고 싶은 열의 번호를 쓰면 됩니다.
예를들어 두번째, 다섯번째열을 늘이고 싶다면 android:stretchColumns="1,4"로 쓰면 되고 전체열은 *을 쓰면됩니다^^
