### ISSUE TITLE
 Sub quest1 과 똑같이 만들어지지가 않습니다.

### ISSUE THREAD

**Issue by Kojiwoong** [Jaram2017/android-findpeople#12]
첫번째 코드 예시입니다.
https://github.com/Jaram2017/android-findpeople/blob/877500a0b8854f02881bc456952a6458b52ec91b/first%20activity.xml

![Imgur](https://i.imgur.com/pNduM57.png)

두번째 코드 예시입니다.
https://github.com/Jaram2017/android-findpeople/blob/Jiwoong/secondActivity.xml

![Imgur](https://i.imgur.com/4BMZjjK.png)
보시다시피 아예 나오지가 않습니다.

**Comment by Kojiwoong** [comment]
최대한 비슷하게 만들어봤습니다.

![Imgur](https://i.imgur.com/VPMhcbp.png)

**Comment by Kojiwoong** [comment]
세번째 코드입니다.

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.retina.thirdactivity.MainActivity">

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="match_parent"
        android:orientation="vertical"
        tools:layout_editor_absoluteY="0dp"
        tools:layout_editor_absoluteX="8dp">

        <Button
            android:id="@+id/button01"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="NEW FOLDER" />

        <Button
            android:id="@+id/button02"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="WEEK" />

        <Button
            android:id="@+id/button03"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="PERSONAL" />

        <Button
            android:id="@+id/button04"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="MEMO" />

        <Button
            android:id="@+id/button05"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="+CREATE INDEX" />
    </LinearLayout>

</android.support.constraint.ConstraintLayout>

**Comment by jshagold** [comment]
일단 두번째는 안드로이드스튜디오가 친절하게  에러메세지를 보내줬어요
그거보고도 해결이안되면 다시물어봐주세요

**Comment by Kojiwoong** [comment]
두번째는 
one or more layouts are missing the layout_width and layout_height attributes 에러 메시지랑
일부러 같이 찍은건데  
일단은 최대한 풀어보려 해보고 다시 쓰겠습니다.

**Comment by jshagold** [comment]
형 첫번째것도
안드로이드스튜디오에서 어디서 문제가 생겼는지 다말해주는데요.....
”Vertical“ 이건 어디서 복사해서 붙이셨나요.... "" 이 따옴표를 써야죠...

**Comment by Hann** [comment]
@Kojiwoong 안드로이드 스튜디오에서 에러 표시 뜰텐데 안보고 이슈 올린거예요?

**Comment by Hann** [comment]
그리고 사람을 부를때는 assign기능과 컨텐츠에 언급기능을 활용하세요

**Comment by Hann** [comment]
이슈 해결은 커밋으로 보여주세요. 해결 한건가요?

**Comment by Kojiwoong** [comment]
@Hann 해결 되었습니다.
![Imgur](https://i.imgur.com/kgbg8zG.png)

**Comment by Hann** [comment]
잘했는데, 스샷말고 commit을 올리세요

**Comment by Kojiwoong** [comment]
@Hann 일단 commit은 올렸는데 해결은 되었다고 봐야할까요?

**Comment by Hann** [comment]
커밋을 여기 이슈에 올리세요. 링크 첨부

**Comment by Kojiwoong** [comment]
https://github.com/Jaram2017/android-findpeople/blob/Jiwoong/AboutIssue.xml

**Comment by Hann** [comment]
그건 커밋이아니라 파일입니다

**Comment by Kojiwoong** [comment]
https://github.com/Jaram2017/android-findpeople/commit/5399f37c74e7a2f8ff6d7884688a6045ae9e5213
