### ISSUE TITLE
sub quest 1

### ISSUE THREAD

**Issue by jshagold** [Jaram2017/android-findpeople#5]
![screenshot_2017-09-19-20-24-47](https://user-images.githubusercontent.com/26281152/30696458-ac1dc82e-9f16-11e7-85df-982ddcae3d25.png)
이미지처럼 화면을 만들어보세요! (LinearLayout사용)

**Comment by jshagold** [comment]
기능같은거 한개도 안넣어도돼요!! 화면만 구성해보세요!

**Comment by Kojiwoong** [comment]
한번 도전해보겠습니다. 일단 저번에 말했던 haxm다운 안받았던 거는 
무조건 받아야하네요. 안드로이드 스튜디오 가상머신 돌리려면 ㅋㅋ

**Comment by jshagold** [comment]
sub quest2를 줘서 sub quest1은 닫습니다.
