### ISSUE TITLE
sub quest1 해보는 도중에 궁금한 점인데

### ISSUE THREAD

**Issue by Kojiwoong** [Jaram2017/android-findpeople#8]
![Imgur](https://i.imgur.com/xcWFihB.png)  
위 사진처럼 LinearLayout에서  
Text를 넣어서 sub quest 주어진 사진처럼 만들어보려고 했었는데  
밑에 줄이 그어지네요.  
혹시 왜 줄이 그어지는지 알 수 있을까요?  

***
다음은 XML 스크립트입니다.  
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.retina.test.MainActivity">

    <LinearLayout
        android:id="@+id/NewFolder"
        android:layout_width="215dp"
        android:layout_height="69dp"
        android:orientation="horizontal"
        tools:layout_editor_absoluteX="16dp"
        tools:layout_editor_absoluteY="16dp">

        <EditText
            android:id="@+id/editText"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:ems="10"
            android:inputType="textPersonName"
            android:text="New Folder" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="215dp"
        android:layout_height="69dp"
        android:orientation="horizontal"
        tools:layout_editor_absoluteX="16dp"
        tools:layout_editor_absoluteY="87dp">

        <EditText
            android:id="@+id/editText2"
            android:layout_width="wrap_content"
            android:layout_height="87dp"
            android:ems="10"
            android:inputType="textPersonName"
            android:text="Week" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="215dp"
        android:layout_height="69dp"
        android:layout_marginLeft="16dp"
        android:orientation="horizontal"
        app:layout_constraintLeft_toLeftOf="parent"
        tools:layout_editor_absoluteY="173dp">

        <EditText
            android:id="@+id/editText3"
            android:layout_width="wrap_content"
            android:layout_height="87dp"
            android:ems="10"
            android:inputType="textPersonName"
            android:text="Personal" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="215dp"
        android:layout_height="69dp"
        android:layout_marginLeft="16dp"
        android:orientation="horizontal"
        app:layout_constraintLeft_toLeftOf="parent"
        tools:layout_editor_absoluteY="173dp">

    </LinearLayout>

    <EditText
        android:id="@+id/editText4"
        android:layout_width="wrap_content"
        android:layout_height="87dp"
        android:ems="10"
        android:inputType="textPersonName"
        android:text="Memo"
        tools:layout_editor_absoluteX="16dp"
        tools:layout_editor_absoluteY="257dp" />
</android.support.constraint.ConstraintLayout>

**Comment by jshagold** [comment]
전체코드 보여주세요

**Comment by YongTaek** [comment]
EditText 말고 TextView 쓰세요..

**Comment by Kojiwoong** [comment]
TextView로 설정하고 다시 한번 해볼게요;; 제가 시작한지 얼마 안되서 그냥 영상이랑 책 보면서 따라해보고 있습니다.

**Comment by Kojiwoong** [comment]
다시 처음부터 새로 짜보겠습니다.
